[build]
  command = "pnpm install --frozen-lockfile && pnpm run build --verbose"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8"
  SECRETS_SCAN_ENABLED = "false"
  NPM_FLAGS = "--version"
  COREPACK_ENABLE_STRICT = "0"

# Disable secrets scanning entirely since we've removed actual secret values
[build.processing.secrets]
  enabled = false

# Configure for NestJS serverless functions
[functions]
  directory = "netlify/functions"

# Redirect all API routes to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/vapi/*"
  to = "/.netlify/functions/api/vapi/:splat"
  status = 200

[[redirects]]
  from = "/twilio/*"
  to = "/.netlify/functions/api/twilio/:splat"
  status = 200

# Catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200